//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitySolution.EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ItemName2 { get; set; }
        public string ItemImageURL { get; set; }
        public string Description { get; set; }
        public string ItemPrice { get; set; }
        public string Active { get; set; }
        public string Hot { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string KeySearch { get; set; }
        public string CategoryName { get; set; }
        public string Description2 { get; set; }
        public string ItemCondition { get; set; }
    }
}
