//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitySolution.EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string Title { get; set; }
        public string MainContent { get; set; }
        public string MainContent2 { get; set; }
        public string ItemImageURL { get; set; }
        public string Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string KeySearch { get; set; }
        public string Description { get; set; }
        public string Description2 { get; set; }
        public string Title2 { get; set; }
    }
}
